[package]
name = "__PACKAGE_NAME__"
version = "0.1.0"
edition = "2021"

[lib]
name = "__CRATE_NAME__"
crate-type = ["cdylib"]

[dependencies]
fui-rs = { path = "node_modules/@effindomv2/fui-rs" }

[features]
native-runtime = ["fui-rs/native-runtime"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
